
CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE,
 password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'owner',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS cars (
 id BIGSERIAL PRIMARY KEY, owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 brand TEXT NOT NULL, model TEXT NOT NULL, plate TEXT NOT NULL, year INT NOT NULL,
 status TEXT NOT NULL DEFAULT 'available' CHECK(status IN ('available','rented','maintenance')),
 revenue NUMERIC(12,2) NOT NULL DEFAULT 0, location TEXT NOT NULL DEFAULT 'Санкт-Петербург',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cars_owner_idx ON cars(owner_id);
CREATE TABLE IF NOT EXISTS rentals (
 id BIGSERIAL PRIMARY KEY, owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 car_name TEXT NOT NULL, client_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending',
 amount NUMERIC(12,2) NOT NULL DEFAULT 0, starts_at TIMESTAMPTZ, ends_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS verifications (
 id BIGSERIAL PRIMARY KEY, owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, stage TEXT NOT NULL,
 score INT NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'review', created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS leads (
 id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL, email TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
