
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT 'Санкт-Петербург';
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS users_phone_unique ON users(phone) WHERE phone IS NOT NULL;

ALTER TABLE cars ADD COLUMN IF NOT EXISTS daily_price NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS mileage INT NOT NULL DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS color TEXT NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vin TEXT NOT NULL DEFAULT '';

ALTER TABLE rentals ADD COLUMN IF NOT EXISTS client_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS ends_at TIMESTAMPTZ;

ALTER TABLE verifications ADD COLUMN IF NOT EXISTS progress INT NOT NULL DEFAULT 20;
ALTER TABLE verifications ADD COLUMN IF NOT EXISTS risk_level TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE verifications ADD COLUMN IF NOT EXISTS client_phone TEXT NOT NULL DEFAULT '';

UPDATE cars SET daily_price = CASE brand
  WHEN 'Kia' THEN 4900 WHEN 'Geely' THEN 6200 WHEN 'Toyota' THEN 5200
  WHEN 'Haval' THEN 4100 WHEN 'BMW' THEN 7200 WHEN 'Chery' THEN 3900 ELSE 4500 END
WHERE daily_price=0;
