CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS fleet_profiles (
  id BIGSERIAL PRIMARY KEY,
  owner_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT 'Санкт-Петербург',
  published BOOLEAN NOT NULL DEFAULT true,
  rating NUMERIC(3,2) NOT NULL DEFAULT 5.00,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS public_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'Седан';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seats INT NOT NULL DEFAULT 5;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS transmission TEXT NOT NULL DEFAULT 'Автомат';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel TEXT NOT NULL DEFAULT 'Бензин';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS deposit NUMERIC(12,2) NOT NULL DEFAULT 20000;

ALTER TABLE rentals ADD COLUMN IF NOT EXISTS car_id BIGINT REFERENCES cars(id) ON DELETE SET NULL;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS client_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'owner';
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS booking_code TEXT;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS deposit NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'unpaid';
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS hold_expires_at TIMESTAMPTZ;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS pickup_location TEXT NOT NULL DEFAULT '';
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS dropoff_location TEXT NOT NULL DEFAULT '';
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS cancellation_reason TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS rentals_booking_code_unique ON rentals(booking_code) WHERE booking_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS rentals_car_dates_idx ON rentals(car_id, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS rentals_customer_idx ON rentals(client_user_id);

UPDATE cars SET public_enabled=true WHERE public_enabled IS NULL;
