ALTER TABLE fleet_profiles ADD COLUMN IF NOT EXISTS logo_url TEXT NOT NULL DEFAULT '';
ALTER TABLE fleet_profiles ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '';
ALTER TABLE fleet_profiles ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';
ALTER TABLE fleet_profiles ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';

ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_volume TEXT NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS horsepower INT NOT NULL DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS drive_type TEXT NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel_consumption TEXT NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS tank_volume TEXT NOT NULL DEFAULT '';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS maintenance_interval INT NOT NULL DEFAULT 0;
